Delete an active user

diff --git a/scripts/02 b/scripts/02
--- a/scripts/02
+++ b/scripts/02
@@ -4,26 +4,36 @@ USER=$1
 
 if [ -z $USER ]; then
 	echo "Error: no user name provided"
-	exit
+	exit 1
 fi
 
 getent passwd $USER &> /dev/null
 
 if [ $? -ne 0 ]; then
 	echo "Error: user '$USER' does not exist"
-	exit
+	exit 1
 fi
 
 who | grep $USER &> /dev/null
 
 if [ $? -ne 0 ]; then
 	echo "Error: the '$USER' is not logged in"
-	exit
+	exit 1
 fi
 
 if [ "$(whoami)" != "root" ]; then
 	echo "Error: permission denied"
-	exit
+	exit 1
 fi
 
 kill $(pgrep -u $USER) &> /dev/null
+userdel -r $USER &> /dev/null
+
+getent passwd $USER &> /dev/null
+
+if [ $? -eq 0 ]; then
+	echo "Error: could not delete active user '$USER'"
+	exit 1
+else
+	echo "Successfully deleted active user '$USER'"
+fi
